package com.ajr;

import com.ajr.model.Cargo;
import com.ajr.model.Curriculo;
import com.ajr.model.Etapa;
import com.ajr.model.ProcessoSeletivo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import com.ajr.repository.CargoRepository;
import com.ajr.repository.CurriculoRepository;
import com.ajr.repository.EtapaRepository;
import com.ajr.repository.ProcessoSeletivoRepository;

@RestController    // This means that this class is a Controller
@RequestMapping(path = "/ajr") // This means URL's start with /demo (after Application path)
public class MainController {

    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired // This means to get the bean called userRepository
    private CargoRepository cargoRepository;
    @Autowired // This means to get the bean called userRepository
    private ProcessoSeletivoRepository processoSelRepository;
    @Autowired // This means to get the bean called userRepository
    private EtapaRepository etapaRepository;
    @Autowired // This means to get the bean called userRepository
    private CurriculoRepository curriculoRepository;

    @GetMapping(path = "/allCurriculos")
    public @ResponseBody
    Iterable<Curriculo> getAllCurriculos() {
        // This returns a JSON or XML with the users
        return curriculoRepository.findAll();
    }

    @PostMapping("/gravarCurriculo")
    Curriculo gravarTamanhos(@RequestBody Curriculo curriculo) {
        return curriculoRepository.save(curriculo);
    }
    @GetMapping(path = "/allEtapas")
    public @ResponseBody
    Iterable<Etapa> getAllEtapas() {
        // This returns a JSON or XML with the users
        return etapaRepository.findAll();
    }

    @PostMapping("/gravarEtapa")
    Etapa gravarTamanhos(@RequestBody Etapa etapa) {
        return etapaRepository.save(etapa);
    }
    @GetMapping(path = "/allProcessosSeletivos")
    public @ResponseBody
    Iterable<ProcessoSeletivo> getAllProcessoSeletivo() {
        // This returns a JSON or XML with the users
        return processoSelRepository.findAll();
    }

    @PostMapping("/gravarProcessoSeletivo")
    ProcessoSeletivo gravarProcessoSeletivo(@RequestBody ProcessoSeletivo processoSeletivo) {
        return processoSelRepository.save(processoSeletivo);
    }
    @GetMapping(path = "/allCargos")
    public @ResponseBody
    Iterable<Cargo> getAllCargos() {
        // This returns a JSON or XML with the users
        return cargoRepository.findAll();
    }

    @PostMapping("/gravarCargo")
    Cargo gravarProcessoSeletivo(@RequestBody Cargo cargo) {
        return cargoRepository.save(cargo);
    }

}
